#!/usr/bin/env bash
set -euo pipefail

DST="keyboards/cyboard/imprint/imprint_number_row_5key_bottom_row"

echo "Creating default keymap from vial keymap..."
cp -r "$DST/keymaps/vial" "$DST/keymaps/default"

echo "Removing VIAL-specific options from default keymap..."
sed -i '/VIAL_ENABLE/d' "$DST/keymaps/default/rules.mk"
sed -i '/VIA_ENABLE/d' "$DST/keymaps/default/rules.mk"
sed -i '/QMK_SETTINGS/d' "$DST/keymaps/default/rules.mk"
sed -i '/TAP_DANCE_ENABLE/d' "$DST/keymaps/default/rules.mk"
sed -i '/COMBO_ENABLE/d' "$DST/keymaps/default/rules.mk"
sed -i '/KEY_OVERRIDE_ENABLE/d' "$DST/keymaps/default/rules.mk"

echo "Created default keymap: $DST/keymaps/default"
